/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-03-06 10:24:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar", Long.valueOf(1364130896000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl.release();
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"container-fluid py-4\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-xl-0 mb-4\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <div class=\"numbers\">\r\n");
      out.write("                    <p class=\"text-sm mb-0 text-uppercase font-weight-bold\" style=\"font-size: 14px !important;\">Tổng Tiền Quyên Góp</p>\r\n");
      out.write("                    <h5 class=\"font-weight-bolder\" style=\"font-size: 20px;\">\r\n");
      out.write("                      53.000.000.000Đ\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <p class=\"mb-0\" style=\"font-size: 15px;\">\r\n");
      out.write("                      <span class=\"text-success text-sm font-weight-bolder\">+25%</span>\r\n");
      out.write("                      so với năm ngoái\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4 text-end\">\r\n");
      out.write("                  <div class=\"icon icon-shape bg-gradient-primary shadow-primary text-center rounded-circle\">\r\n");
      out.write("                    <i class=\"ni ni-money-coins text-lg opacity-10\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-xl-0 mb-4\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <div class=\"numbers\">\r\n");
      out.write("                    <p class=\"text-sm mb-0 text-uppercase font-weight-bold\" style=\"font-size: 13px !important;\">Người Dùng Hôm Nay</p>\r\n");
      out.write("                    <h5 class=\"font-weight-bolder\">\r\n");
      out.write("                      100\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <p class=\"mb-0\">\r\n");
      out.write("                      <span class=\"text-success text-sm font-weight-bolder\">+3%</span>\r\n");
      out.write("                      so với hôm qua\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4 text-end\">\r\n");
      out.write("                  <div class=\"icon icon-shape bg-gradient-danger shadow-danger text-center rounded-circle\">\r\n");
      out.write("                    <i class=\"ni ni-world text-lg opacity-10\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6 mb-xl-0 mb-4\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <div class=\"numbers\">\r\n");
      out.write("                    <p class=\"text-sm mb-0 text-uppercase font-weight-bold\">Quyên Góp Hôm Nay</p>\r\n");
      out.write("                    <h5 class=\"font-weight-bolder\">\r\n");
      out.write("                      3.000.000Đ\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <p class=\"mb-0\">\r\n");
      out.write("                      <span class=\"text-danger text-sm font-weight-bolder\">-2%</span>\r\n");
      out.write("                      so với hôm qua\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4 text-end\">\r\n");
      out.write("                  <div class=\"icon icon-shape bg-gradient-success shadow-success text-center rounded-circle\">\r\n");
      out.write("                    <i class=\"ni ni-paper-diploma text-lg opacity-10\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-3 col-sm-6\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <div class=\"numbers\">\r\n");
      out.write("                    <p class=\"text-sm mb-0 text-uppercase font-weight-bold\">Đang Diễn Ra</p>\r\n");
      out.write("                    <h5 class=\"font-weight-bolder\">\r\n");
      out.write("                      13 Đợt\r\n");
      out.write("                    </h5>\r\n");
      out.write("                    <p class=\"mb-0\">\r\n");
      out.write("                      <span class=\"text-success text-sm font-weight-bolder\">+5%</span> so với tháng rồi\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4 text-end\">\r\n");
      out.write("                  <div class=\"icon icon-shape bg-gradient-warning shadow-warning text-center rounded-circle\">\r\n");
      out.write("                    <i class=\"ni ni-cart text-lg opacity-10\" aria-hidden=\"true\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row mt-4\">\r\n");
      out.write("        <div class=\"col-lg-7 mb-lg-0 mb-4\">\r\n");
      out.write("          <div class=\"card z-index-2 h-100\">\r\n");
      out.write("            <div class=\"card-header pb-0 pt-3 bg-transparent\">\r\n");
      out.write("              <h6 class=\"text-capitalize\">Tổng Quan Quyên Góp</h6>\r\n");
      out.write("              <p class=\"text-sm mb-0\">\r\n");
      out.write("                <i class=\"fa fa-arrow-up text-success\"></i>\r\n");
      out.write("                <span class=\"font-weight-bold\">4% more</span> in 2022\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <div class=\"chart\">\r\n");
      out.write("                <canvas id=\"chart-line\" class=\"chart-canvas\" height=\"300\"></canvas>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-5\">\r\n");
      out.write("          <div class=\"card card-carousel overflow-hidden h-100 p-0\">\r\n");
      out.write("            <div id=\"carouselExampleCaptions\" class=\"carousel slide h-100\" data-bs-ride=\"carousel\">\r\n");
      out.write("              <div class=\"carousel-inner border-radius-lg h-100\">\r\n");
      out.write("                <div class=\"carousel-item h-100 active\" style=\"background-image: url('template/admin/assets/img/carousel-1.jpg');\r\n");
      out.write("      background-size: cover;\">\r\n");
      out.write("                  <div class=\"carousel-caption d-none d-md-block bottom-0 text-start start-0 ms-5\">\r\n");
      out.write("                    <div class=\"icon icon-shape icon-sm bg-white text-center border-radius-md mb-3\">\r\n");
      out.write("                      <i class=\"ni ni-camera-compact text-dark opacity-10\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-white mb-1\">Mọi thứ rồi sẽ qua đi</h5>\r\n");
      out.write("                    <p>chỉ còn tình người là ở lại.</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item h-100\" style=\"background-image: url('template/admin/assets/img/carousel-2.jpg');\r\n");
      out.write("      background-size: cover;\">\r\n");
      out.write("                  <div class=\"carousel-caption d-none d-md-block bottom-0 text-start start-0 ms-5\">\r\n");
      out.write("                    <div class=\"icon icon-shape icon-sm bg-white text-center border-radius-md mb-3\">\r\n");
      out.write("                      <i class=\"ni ni-bulb-61 text-dark opacity-10\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-white mb-1\">Yêu thương mà chúng ta cho đi</h5>\r\n");
      out.write("                    <p>là yêu thương mà chúng ta giữ được.</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item h-100\" style=\"background-image: url('template/admin/assets/img/carousel-3.jpg');\r\n");
      out.write("      background-size: cover;\">\r\n");
      out.write("                  <div class=\"carousel-caption d-none d-md-block bottom-0 text-start start-0 ms-5\">\r\n");
      out.write("                    <div class=\"icon icon-shape icon-sm bg-white text-center border-radius-md mb-3\">\r\n");
      out.write("                      <i class=\"ni ni-trophy text-dark opacity-10\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-white mb-1\">Bạn sẽ tìm thấy niềm vui</h5>\r\n");
      out.write("                    <p>khi giúp đỡ người khác bằng tất cả tấm lòng.</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <button class=\"carousel-control-prev w-5 me-3\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("              </button>\r\n");
      out.write("              <button class=\"carousel-control-next w-5 me-3\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row mt-4\">\r\n");
      out.write("        <div class=\"col-lg-7 mb-lg-0 mb-4\">\r\n");
      out.write("          <div class=\"card \">\r\n");
      out.write("            <div class=\"card-header pb-0 p-3\">\r\n");
      out.write("              <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <h6 class=\"mb-2\">Lịch Sử Quyên Góp</h6>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("              <table class=\"table align-items-center \">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"w-30\">\r\n");
      out.write("                      <div class=\"d-flex px-2 py-1 align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <img src=\"template/admin/assets/img/icons/flags/US.png\" alt=\"Country flag\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                          <p class=\"text-xs font-weight-bold mb-0\">Country:</p>\r\n");
      out.write("                          <h6 class=\"text-sm mb-0\">United States</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div class=\"text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Sales:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">2500</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div class=\"text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Value:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">$230,900</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"align-middle text-sm\">\r\n");
      out.write("                      <div class=\"col text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Bounce:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">29.9%</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"w-30\">\r\n");
      out.write("                      <div class=\"d-flex px-2 py-1 align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <img src=\"template/admin/assets/img/icons/flags/DE.png\" alt=\"Country flag\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                          <p class=\"text-xs font-weight-bold mb-0\">Country:</p>\r\n");
      out.write("                          <h6 class=\"text-sm mb-0\">Germany</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div class=\"text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Sales:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">3.900</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div class=\"text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Value:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">$440,000</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"align-middle text-sm\">\r\n");
      out.write("                      <div class=\"col text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Bounce:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">40.22%</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"w-30\">\r\n");
      out.write("                      <div class=\"d-flex px-2 py-1 align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <img src=\"template/admin/assets/img/icons/flags/GB.png\" alt=\"Country flag\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                          <p class=\"text-xs font-weight-bold mb-0\">Country:</p>\r\n");
      out.write("                          <h6 class=\"text-sm mb-0\">Great Britain</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div class=\"text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Sales:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">1.400</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div class=\"text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Value:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">$190,700</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"align-middle text-sm\">\r\n");
      out.write("                      <div class=\"col text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Bounce:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">23.44%</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"w-30\">\r\n");
      out.write("                      <div class=\"d-flex px-2 py-1 align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <img src=\"template/admin/assets/img/icons/flags/BR.png\" alt=\"Country flag\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ms-4\">\r\n");
      out.write("                          <p class=\"text-xs font-weight-bold mb-0\">Country:</p>\r\n");
      out.write("                          <h6 class=\"text-sm mb-0\">Brasil</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div class=\"text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Sales:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">562</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <div class=\"text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Value:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">$143,960</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"align-middle text-sm\">\r\n");
      out.write("                      <div class=\"col text-center\">\r\n");
      out.write("                        <p class=\"text-xs font-weight-bold mb-0\">Bounce:</p>\r\n");
      out.write("                        <h6 class=\"text-sm mb-0\">32.14%</h6>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-5\">\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header pb-0 p-3\">\r\n");
      out.write("              <h6 class=\"mb-0\">Hạng Mục Quyên Góp</h6>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body p-3\">\r\n");
      out.write("              <ul class=\"list-group\">\r\n");
      out.write("                <li class=\"list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg\">\r\n");
      out.write("                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center\">\r\n");
      out.write("                      <i class=\"ni ni-mobile-button text-white opacity-10\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex flex-column\">\r\n");
      out.write("                      <h6 class=\"mb-1 text-dark text-sm\">Devices</h6>\r\n");
      out.write("                      <span class=\"text-xs\">250 in stock, <span class=\"font-weight-bold\">346+ sold</span></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"d-flex\">\r\n");
      out.write("                    <button class=\"btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto\"><i class=\"ni ni-bold-right\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg\">\r\n");
      out.write("                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center\">\r\n");
      out.write("                      <i class=\"ni ni-tag text-white opacity-10\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex flex-column\">\r\n");
      out.write("                      <h6 class=\"mb-1 text-dark text-sm\">Tickets</h6>\r\n");
      out.write("                      <span class=\"text-xs\">123 closed, <span class=\"font-weight-bold\">15 open</span></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"d-flex\">\r\n");
      out.write("                    <button class=\"btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto\"><i class=\"ni ni-bold-right\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"list-group-item border-0 d-flex justify-content-between ps-0 mb-2 border-radius-lg\">\r\n");
      out.write("                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center\">\r\n");
      out.write("                      <i class=\"ni ni-box-2 text-white opacity-10\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex flex-column\">\r\n");
      out.write("                      <h6 class=\"mb-1 text-dark text-sm\">Error logs</h6>\r\n");
      out.write("                      <span class=\"text-xs\">1 is active, <span class=\"font-weight-bold\">40 closed</span></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"d-flex\">\r\n");
      out.write("                    <button class=\"btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto\"><i class=\"ni ni-bold-right\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"list-group-item border-0 d-flex justify-content-between ps-0 border-radius-lg\">\r\n");
      out.write("                  <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"icon icon-shape icon-sm me-3 bg-gradient-dark shadow text-center\">\r\n");
      out.write("                      <i class=\"ni ni-satisfied text-white opacity-10\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex flex-column\">\r\n");
      out.write("                      <h6 class=\"mb-1 text-dark text-sm\">Happy users</h6>\r\n");
      out.write("                      <span class=\"text-xs font-weight-bold\">+ 430</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"d-flex\">\r\n");
      out.write("                    <button class=\"btn btn-link btn-icon-only btn-rounded btn-sm text-dark icon-move-right my-auto\"><i class=\"ni ni-bold-right\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /admin/jsp/index.jsp(6,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_eval_c_005fimport_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_c_005fimport_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_c_005fimport_005f0[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fimport_005f0);
          }
          do {
            out.write('\r');
            out.write('\n');
            out.write('	');
            if (_jspx_meth_c_005fparam_005f0(_jspx_th_c_005fimport_005f0, _jspx_page_context, _jspx_push_body_count_c_005fimport_005f0))
              return true;
            out.write('\r');
            out.write('\n');
            out.write('	');
            int evalDoAfterBody = _jspx_th_c_005fimport_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_c_005fimport_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_c_005fimport_005f0[0]--;
          }
        }
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fimport_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fimport_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f0_reused = false;
    try {
      _jspx_th_c_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fimport_005f0);
      // /admin/jsp/index.jsp(7,1) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setName("title");
      // /admin/jsp/index.jsp(7,1) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setValue("Trang chủ Admin");
      int _jspx_eval_c_005fparam_005f0 = _jspx_th_c_005fparam_005f0.doStartTag();
      if (_jspx_th_c_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f0);
      _jspx_th_c_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /admin/jsp/index.jsp(385,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
