/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-02-20 13:43:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar", Long.valueOf(1364130896000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" style=\" font-size: 17px;\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">  \r\n");
      out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/apple-icon.png\">\r\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/favicon.png\">\r\n");
      out.write("  <title>\r\n");
      out.write("    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("  </title>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Fonts and icons -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- Nucleo Icons -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/nucleo-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/nucleo-svg.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- Font Awesome Icons -->\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/42d5adcbca.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/nucleo-svg.css\" rel=\"stylesheet\" />\r\n");
      out.write("  \r\n");
      out.write(" <!-- CSS Files -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main.css\">\r\n");
      out.write("  <link id=\"pagestyle\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/argon-dashboard.css?v=2.0.4\" rel=\"stylesheet\" />\r\n");
      out.write("  <link	href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" integrity=\"sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN\" crossorigin=\"anonymous\"/>	\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.2/css/all.css\" integrity=\"sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay\"\r\n");
      out.write("		crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\"\r\n");
      out.write("		href=\"https://use.fontawesome.com/releases/v5.8.2/css/all.css\"\r\n");
      out.write("		integrity=\"sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay\"\r\n");
      out.write("		crossorigin=\"anonymous\">\r\n");
      out.write("		\r\n");
      out.write("  <!-- jQuery library -->\r\n");
      out.write("  <script	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("  <!-- Latest compiled JavaScript -->\r\n");
      out.write("  <script src=\"//code.jquery.com/jquery.js\"></script>\r\n");
      out.write("  <script src=\"http://code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css\">\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">	\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.ckeditor.com/4.20.1/full/ckeditor.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ckfinder/ckfinder.js\"></script> \r\n");
      out.write(" 	\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"g-sidenav-show bg-gray-100\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"min-height-300 bg-primary position-absolute w-100\"></div>\r\n");
      out.write("  <aside class=\"sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 \" id=\"sidenav-main\" style=\"z-index: 1040;\">\r\n");
      out.write("    <div class=\"sidenav-header\">\r\n");
      out.write("      <i class=\"fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none\" aria-hidden=\"true\" id=\"iconSidenav\"></i>\r\n");
      out.write("      <a class=\"navbar-brand m-0 logo\" href=\"#\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/logo-ct-dark.png\" class=\"navbar-brand-img\" alt=\"main_logo\" style=\"float: left;\">\r\n");
      out.write("        <span class=\"ms-1 font-weight-bold\">Website Từ Thiện</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr class=\"horizontal dark mt-0\">\r\n");
      out.write("    <div class=\"collapse navbar-collapse  w-auto \" id=\"sidenav-collapse-main\">\r\n");
      out.write("      <ul class=\"navbar-nav\">\r\n");
      out.write("      \r\n");
      out.write("        <li class=\"nav-item mt-3\" style=\"margin-left: -7%;\">\r\n");
      out.write("	        <a class=\"nav-link index\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DonationsController?action=index\">\r\n");
      out.write("	          <h6 class=\"text-uppercase text-xs font-weight-bolder opacity-6\" style=\"font-size: 110% !important;\"><i class=\"fa fa-home\" style=\"font-size:20px;color:#00FFFF\"></i>Trang chủ</h6>\r\n");
      out.write("	        </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link DonationList\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/DonationsController?action=DonationList\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni ni-calendar-grid-58 text-warning text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\">Đợt Quyên Góp</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link UserList\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/UsersController?action=UserList\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni ni-single-02 text-dark text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\">Người Dùng</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link \" href=\"./pages/billing.html\">\r\n");
      out.write("            <div class=\"icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center\">\r\n");
      out.write("              <i class=\"ni ni-credit-card text-success text-sm opacity-10\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"nav-link-text ms-1\">Người Dùng Quyên Góp</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>        \r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("  <main class=\"main-content position-relative border-radius-lg \">\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl \" id=\"navbarBlur\" data-scroll=\"false\">\r\n");
      out.write("      <div class=\"container-fluid py-1 px-3\">\r\n");
      out.write("        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("          <ol class=\"breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5\">\r\n");
      out.write("            <li class=\"breadcrumb-item text-sm\"><a class=\"opacity-5 text-white\" href=\"javascript:;\"><i class=\"fa fa-home\"></i> Trang chủ</a></li>\r\n");
      out.write("            <li class=\"breadcrumb-item text-sm text-white active\" aria-current=\"page\" id=\"str-pages1\"></li>\r\n");
      out.write("          </ol>\r\n");
      out.write("          <h6 class=\"font-weight-bolder text-white mb-0\" id=\"str-pages2\">Trang Chủ</h6>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4\" id=\"navbar\">          \r\n");
      out.write("          <ul class=\"navbar-nav justify-content-end\" style=\"padding-left: 80%;\">\r\n");
      out.write("          	<li class=\"nav-item d-flex align-items-center\">\r\n");
      out.write("          		<div class=\"btn-group\">\r\n");
      out.write("				  <a type=\"button\" class=\"text-white font-weight-bold dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("				    Xin chào, Admin!\r\n");
      out.write("				  </a>\r\n");
      out.write("				  <div class=\"dropdown-menu\">				  \r\n");
      out.write("				    <a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/UsersController?action=logout\">Đăng xuất</a>\r\n");
      out.write("				  </div>\r\n");
      out.write("				</div>          	\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white font-weight-bold px-0\">              \r\n");
      out.write("                <i class=\"fa fa-user me-sm-1\" style=\"padding-left: 50%;\"></i>                \r\n");
      out.write("              </a>   \r\n");
      out.write("            </li>          \r\n");
      out.write("            <li class=\"nav-item d-xl-none ps-3 d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white p-0\" id=\"iconNavbarSidenav\">\r\n");
      out.write("                <div class=\"sidenav-toggler-inner\">\r\n");
      out.write("                  <i class=\"sidenav-toggler-line bg-white\"></i>\r\n");
      out.write("                  <i class=\"sidenav-toggler-line bg-white\"></i>\r\n");
      out.write("                  <i class=\"sidenav-toggler-line bg-white\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item px-3 d-flex align-items-center\">\r\n");
      out.write("              <a href=\"javascript:;\" class=\"nav-link text-white p-0\">\r\n");
      out.write("                <i class=\"fa fa-cog fixed-plugin-button-nav cursor-pointer\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <!-- End Navbar -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
