/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-02-28 00:58:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.welfare_002dgh_002dpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar", Long.valueOf(1364130896000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%209.0/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Welfare - Free Bootstrap 4 Template by Colorlib</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Overpass:300,400,400i,600,700\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("   	  <img src=\"media/logo.jpg\" alt=\"logo\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.html\">Welfare</a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("          <li class=\"nav-item active\"><a href=\"index.html\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"about.html\" class=\"nav-link\">About</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"causes.html\" class=\"nav-link\">Causes</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"donate.html\" class=\"nav-link\">Donate</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"blog.html\" class=\"nav-link\">Blog</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"gallery.html\" class=\"nav-link\">Gallery</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"event.html\" class=\"nav-link\">Events</a></li>\r\n");
      out.write("          <li class=\"nav-item\"><a href=\"contact.html\" class=\"nav-link\">Contact</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("    <!-- END nav -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"hero-wrap\" style=\"background-image: url('images/bg_7.jpg');\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("      <div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row no-gutters slider-text align-items-center justify-content-center\" data-scrollax-parent=\"true\">\r\n");
      out.write("          <div class=\"col-md-7 ftco-animate text-center\" data-scrollax=\" properties: { translateY: '70%' }\">\r\n");
      out.write("            <h1 class=\"mb-4\" data-scrollax=\"properties: { translateY: '30%', opacity: 1.6 }\">Doing Nothing is Not An Option of Our Life</h1>\r\n");
      out.write("            <p class=\"mb-5\" data-scrollax=\"properties: { translateY: '30%', opacity: 1.6 }\">Created by <a href=\"#\">Colorlib.com</a></p>\r\n");
      out.write("\r\n");
      out.write("            <p data-scrollax=\"properties: { translateY: '30%', opacity: 1.6 }\"><a href=\"https://vimeo.com/45830194\" class=\"btn btn-white btn-outline-white px-4 py-3 popup-vimeo\"><span class=\"icon-play mr-2\"></span>Watch Video</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-counter ftco-intro\" id=\"section-counter\">\r\n");
      out.write("    	<div class=\"container\">\r\n");
      out.write("    		<div class=\"row no-gutters\">\r\n");
      out.write("    			<div class=\"col-md-5 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 color-1 align-items-stretch\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("              	<span>Served Over</span>\r\n");
      out.write("                <strong class=\"number\" data-number=\"1432805\">0</strong>\r\n");
      out.write("                <span>Children in 190 countries in the world</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 color-2 align-items-stretch\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("              	<h3 class=\"mb-4\">Donate Money</h3>\r\n");
      out.write("              	<p>Even the all-powerful Pointing has no control about the blind texts.</p>\r\n");
      out.write("              	<p><a href=\"#\" class=\"btn btn-white px-3 py-2 mt-2\">Donate Now</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 color-3 align-items-stretch\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("              	<h3 class=\"mb-4\">Be a Volunteer</h3>\r\n");
      out.write("              	<p>Even the all-powerful Pointing has no control about the blind texts.</p>\r\n");
      out.write("              	<p><a href=\"#\" class=\"btn btn-white px-3 py-2 mt-2\">Be A Volunteer</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section\">\r\n");
      out.write("    	<div class=\"container\">\r\n");
      out.write("    		<div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 d-flex services p-3 py-4 d-block\">\r\n");
      out.write("              <div class=\"icon d-flex mb-3\"><span class=\"flaticon-donation-1\"></span></div>\r\n");
      out.write("              <div class=\"media-body pl-4\">\r\n");
      out.write("                <h3 class=\"heading\">Make Donation</h3>\r\n");
      out.write("                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>      \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 d-flex services p-3 py-4 d-block\">\r\n");
      out.write("              <div class=\"icon d-flex mb-3\"><span class=\"flaticon-charity\"></span></div>\r\n");
      out.write("              <div class=\"media-body pl-4\">\r\n");
      out.write("                <h3 class=\"heading\">Become A Volunteer</h3>\r\n");
      out.write("                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>      \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 d-flex services p-3 py-4 d-block\">\r\n");
      out.write("              <div class=\"icon d-flex mb-3\"><span class=\"flaticon-donation\"></span></div>\r\n");
      out.write("              <div class=\"media-body pl-4\">\r\n");
      out.write("                <h3 class=\"heading\">Sponsorship</h3>\r\n");
      out.write("                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>    \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section bg-light\">\r\n");
      out.write("    	<div class=\"container-fluid\">\r\n");
      out.write("    		<div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("          <div class=\"col-md-5 heading-section ftco-animate text-center\">\r\n");
      out.write("            <h2 class=\"mb-4\">Our Causes</h2>\r\n");
      out.write("            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    		<div class=\"row\">\r\n");
      out.write("    			<div class=\"col-md-12 ftco-animate\">\r\n");
      out.write("    				<div class=\"carousel-cause owl-carousel\">\r\n");
      out.write("	    				<div class=\"item\">\r\n");
      out.write("	    					<div class=\"cause-entry\">\r\n");
      out.write("		    					<a href=\"#\" class=\"img\" style=\"background-image: url(images/cause-1.jpg);\"></a>\r\n");
      out.write("		    					<div class=\"text p-3 p-md-4\">\r\n");
      out.write("		    						<h3><a href=\"#\">Clean water for the urban area</a></h3>\r\n");
      out.write("		    						<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>\r\n");
      out.write("		    						<span class=\"donation-time mb-3 d-block\">Last donation 1w ago</span>\r\n");
      out.write("		                <div class=\"progress custom-progress-success\">\r\n");
      out.write("		                  <div class=\"progress-bar bg-primary\" role=\"progressbar\" style=\"width: 28%\" aria-valuenow=\"28\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("		                </div>\r\n");
      out.write("		                <span class=\"fund-raised d-block\">$12,000 raised of $30,000</span>\r\n");
      out.write("		    					</div>\r\n");
      out.write("		    				</div>\r\n");
      out.write("	    				</div>\r\n");
      out.write("	    				<div class=\"item\">\r\n");
      out.write("	    					<div class=\"cause-entry\">\r\n");
      out.write("		    					<a href=\"#\" class=\"img\" style=\"background-image: url(images/cause-2.jpg);\"></a>\r\n");
      out.write("		    					<div class=\"text p-3 p-md-4\">\r\n");
      out.write("		    						<h3><a href=\"#\">Clean water for the urban area</a></h3>\r\n");
      out.write("		    						<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>\r\n");
      out.write("		    						<span class=\"donation-time mb-3 d-block\">Last donation 1w ago</span>\r\n");
      out.write("		                <div class=\"progress custom-progress-success\">\r\n");
      out.write("		                  <div class=\"progress-bar bg-primary\" role=\"progressbar\" style=\"width: 28%\" aria-valuenow=\"28\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("		                </div>\r\n");
      out.write("		                <span class=\"fund-raised d-block\">$12,000 raised of $30,000</span>\r\n");
      out.write("		    					</div>\r\n");
      out.write("		    				</div>\r\n");
      out.write("	    				</div>\r\n");
      out.write("	    				<div class=\"item\">\r\n");
      out.write("	    					<div class=\"cause-entry\">\r\n");
      out.write("		    					<a href=\"#\" class=\"img\" style=\"background-image: url(images/cause-3.jpg);\"></a>\r\n");
      out.write("		    					<div class=\"text p-3 p-md-4\">\r\n");
      out.write("		    						<h3><a href=\"#\">Clean water for the urban area</a></h3>\r\n");
      out.write("		    						<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>\r\n");
      out.write("		    						<span class=\"donation-time mb-3 d-block\">Last donation 1w ago</span>\r\n");
      out.write("		                <div class=\"progress custom-progress-success\">\r\n");
      out.write("		                  <div class=\"progress-bar bg-primary\" role=\"progressbar\" style=\"width: 28%\" aria-valuenow=\"28\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("		                </div>\r\n");
      out.write("		                <span class=\"fund-raised d-block\">$12,000 raised of $30,000</span>\r\n");
      out.write("		    					</div>\r\n");
      out.write("		    				</div>\r\n");
      out.write("	    				</div>\r\n");
      out.write("	    				<div class=\"item\">\r\n");
      out.write("	    					<div class=\"cause-entry\">\r\n");
      out.write("		    					<a href=\"#\" class=\"img\" style=\"background-image: url(images/cause-4.jpg);\"></a>\r\n");
      out.write("		    					<div class=\"text p-3 p-md-4\">\r\n");
      out.write("		    						<h3><a href=\"#\">Clean water for the urban area</a></h3>\r\n");
      out.write("		    						<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>\r\n");
      out.write("		    						<span class=\"donation-time mb-3 d-block\">Last donation 1w ago</span>\r\n");
      out.write("		                <div class=\"progress custom-progress-success\">\r\n");
      out.write("		                  <div class=\"progress-bar bg-primary\" role=\"progressbar\" style=\"width: 28%\" aria-valuenow=\"28\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("		                </div>\r\n");
      out.write("		                <span class=\"fund-raised d-block\">$12,000 raised of $30,000</span>\r\n");
      out.write("		    					</div>\r\n");
      out.write("		    				</div>\r\n");
      out.write("	    				</div>\r\n");
      out.write("	    				<div class=\"item\">\r\n");
      out.write("	    					<div class=\"cause-entry\">\r\n");
      out.write("		    					<a href=\"#\" class=\"img\" style=\"background-image: url(images/cause-5.jpg);\"></a>\r\n");
      out.write("		    					<div class=\"text p-3 p-md-4\">\r\n");
      out.write("		    						<h3><a href=\"#\">Clean water for the urban area</a></h3>\r\n");
      out.write("		    						<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>\r\n");
      out.write("		    						<span class=\"donation-time mb-3 d-block\">Last donation 1w ago</span>\r\n");
      out.write("		                <div class=\"progress custom-progress-success\">\r\n");
      out.write("		                  <div class=\"progress-bar bg-primary\" role=\"progressbar\" style=\"width: 28%\" aria-valuenow=\"28\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("		                </div>\r\n");
      out.write("		                <span class=\"fund-raised d-block\">$12,000 raised of $30,000</span>\r\n");
      out.write("		    					</div>\r\n");
      out.write("		    				</div>\r\n");
      out.write("	    				</div>\r\n");
      out.write("	    				<div class=\"item\">\r\n");
      out.write("	    					<div class=\"cause-entry\">\r\n");
      out.write("		    					<a href=\"#\" class=\"img\" style=\"background-image: url(images/cause-6.jpg);\"></a>\r\n");
      out.write("		    					<div class=\"text p-3 p-md-4\">\r\n");
      out.write("		    						<h3><a href=\"#\">Clean water for the urban area</a></h3>\r\n");
      out.write("		    						<p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life</p>\r\n");
      out.write("		    						<span class=\"donation-time mb-3 d-block\">Last donation 1w ago</span>\r\n");
      out.write("		                <div class=\"progress custom-progress-success\">\r\n");
      out.write("		                  <div class=\"progress-bar bg-primary\" role=\"progressbar\" style=\"width: 28%\" aria-valuenow=\"28\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("		                </div>\r\n");
      out.write("		                <span class=\"fund-raised d-block\">$12,000 raised of $30,000</span>\r\n");
      out.write("		    					</div>\r\n");
      out.write("		    				</div>\r\n");
      out.write("	    				</div>\r\n");
      out.write("    				</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("      	<div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("          <div class=\"col-md-7 heading-section ftco-animate text-center\">\r\n");
      out.write("            <h2 class=\"mb-4\">Latest Donations</h2>\r\n");
      out.write("            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        	<div class=\"col-lg-4 d-flex mb-sm-4 ftco-animate\">\r\n");
      out.write("        		<div class=\"staff\">\r\n");
      out.write("        			<div class=\"d-flex mb-4\">\r\n");
      out.write("        				<div class=\"img\" style=\"background-image: url(images/person_1.jpg);\"></div>\r\n");
      out.write("        				<div class=\"info ml-4\">\r\n");
      out.write("        					<h3><a href=\"teacher-single.html\">Ivan Jacobson</a></h3>\r\n");
      out.write("        					<span class=\"position\">Donated Just now</span>\r\n");
      out.write("        					<div class=\"text\">\r\n");
      out.write("		        				<p>Donated <span>$300</span> for <a href=\"#\">Children Needs Food</a></p>\r\n");
      out.write("		        			</div>\r\n");
      out.write("        				</div>\r\n");
      out.write("        			</div>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"col-lg-4 d-flex mb-sm-4 ftco-animate\">\r\n");
      out.write("        		<div class=\"staff\">\r\n");
      out.write("        			<div class=\"d-flex mb-4\">\r\n");
      out.write("        				<div class=\"img\" style=\"background-image: url(images/person_2.jpg);\"></div>\r\n");
      out.write("        				<div class=\"info ml-4\">\r\n");
      out.write("        					<h3><a href=\"teacher-single.html\">Ivan Jacobson</a></h3>\r\n");
      out.write("        					<span class=\"position\">Donated Just now</span>\r\n");
      out.write("        					<div class=\"text\">\r\n");
      out.write("		        				<p>Donated <span>$150</span> for <a href=\"#\">Children Needs Food</a></p>\r\n");
      out.write("		        			</div>\r\n");
      out.write("        				</div>\r\n");
      out.write("        			</div>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        	<div class=\"col-lg-4 d-flex mb-sm-4 ftco-animate\">\r\n");
      out.write("        		<div class=\"staff\">\r\n");
      out.write("        			<div class=\"d-flex mb-4\">\r\n");
      out.write("        				<div class=\"img\" style=\"background-image: url(images/person_3.jpg);\"></div>\r\n");
      out.write("        				<div class=\"info ml-4\">\r\n");
      out.write("        					<h3><a href=\"teacher-single.html\">Ivan Jacobson</a></h3>\r\n");
      out.write("        					<span class=\"position\">Donated Just now</span>\r\n");
      out.write("        					<div class=\"text\">\r\n");
      out.write("		        				<p>Donated <span>$250</span> for <a href=\"#\">Children Needs Food</a></p>\r\n");
      out.write("		        			</div>\r\n");
      out.write("        				</div>\r\n");
      out.write("        			</div>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-gallery\">\r\n");
      out.write("    	<div class=\"d-md-flex\">\r\n");
      out.write("	    	<a href=\"images/cause-2.jpg\" class=\"gallery image-popup d-flex justify-content-center align-items-center img ftco-animate\" style=\"background-image: url(images/cause-2.jpg);\">\r\n");
      out.write("	    		<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("	    			<span class=\"icon-search\"></span>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</a>\r\n");
      out.write("	    	<a href=\"images/cause-3.jpg\" class=\"gallery image-popup d-flex justify-content-center align-items-center img ftco-animate\" style=\"background-image: url(images/cause-3.jpg);\">\r\n");
      out.write("	    		<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("	    			<span class=\"icon-search\"></span>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</a>\r\n");
      out.write("	    	<a href=\"images/cause-4.jpg\" class=\"gallery image-popup d-flex justify-content-center align-items-center img ftco-animate\" style=\"background-image: url(images/cause-4.jpg);\">\r\n");
      out.write("	    		<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("	    			<span class=\"icon-search\"></span>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</a>\r\n");
      out.write("	    	<a href=\"images/cause-5.jpg\" class=\"gallery image-popup d-flex justify-content-center align-items-center img ftco-animate\" style=\"background-image: url(images/cause-5.jpg);\">\r\n");
      out.write("	    		<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("	    			<span class=\"icon-search\"></span>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</a>\r\n");
      out.write("    	</div>\r\n");
      out.write("    	<div class=\"d-md-flex\">\r\n");
      out.write("	    	<a href=\"images/cause-6.jpg\" class=\"gallery image-popup d-flex justify-content-center align-items-center img ftco-animate\" style=\"background-image: url(images/cause-6.jpg);\">\r\n");
      out.write("	    		<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("	    			<span class=\"icon-search\"></span>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</a>\r\n");
      out.write("	    	<a href=\"images/image_3.jpg\" class=\"gallery image-popup d-flex justify-content-center align-items-center img ftco-animate\" style=\"background-image: url(images/image_3.jpg);\">\r\n");
      out.write("	    		<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("	    			<span class=\"icon-search\"></span>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</a>\r\n");
      out.write("	    	<a href=\"images/image_1.jpg\" class=\"gallery image-popup d-flex justify-content-center align-items-center img ftco-animate\" style=\"background-image: url(images/image_1.jpg);\">\r\n");
      out.write("	    		<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("	    			<span class=\"icon-search\"></span>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</a>\r\n");
      out.write("	    	<a href=\"images/image_2.jpg\" class=\"gallery image-popup d-flex justify-content-center align-items-center img ftco-animate\" style=\"background-image: url(images/image_2.jpg);\">\r\n");
      out.write("	    		<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("	    			<span class=\"icon-search\"></span>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</a>\r\n");
      out.write("	    </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("          <div class=\"col-md-7 heading-section ftco-animate text-center\">\r\n");
      out.write("            <h2 class=\"mb-4\">Recent from blog</h2>\r\n");
      out.write("            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row d-flex\">\r\n");
      out.write("          <div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("          	<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("              <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/image_1.jpg');\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text p-4 d-block\">\r\n");
      out.write("              	<div class=\"meta mb-3\">\r\n");
      out.write("                  <div><a href=\"#\">Sept 10, 2018</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"heading mt-3\"><a href=\"#\">Hurricane Irma has devastated Florida</a></h3>\r\n");
      out.write("                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("          	<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("              <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/image_2.jpg');\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text p-4 d-block\">\r\n");
      out.write("              	<div class=\"meta mb-3\">\r\n");
      out.write("                  <div><a href=\"#\">Sept 10, 2018</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"heading mt-3\"><a href=\"#\">Hurricane Irma has devastated Florida</a></h3>\r\n");
      out.write("                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("          	<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("              <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/image_3.jpg');\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text p-4 d-block\">\r\n");
      out.write("              	<div class=\"meta mb-3\">\r\n");
      out.write("                  <div><a href=\"#\">Sept 10, 2018</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"heading mt-3\"><a href=\"#\">Hurricane Irma has devastated Florida</a></h3>\r\n");
      out.write("                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section bg-light\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("          <div class=\"col-md-7 heading-section ftco-animate text-center\">\r\n");
      out.write("            <h2 class=\"mb-4\">Our Latest Events</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        	<div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("          	<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("              <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/event-1.jpg');\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text p-4 d-block\">\r\n");
      out.write("              	<div class=\"meta mb-3\">\r\n");
      out.write("                  <div><a href=\"#\">Sep. 10, 2018</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"heading mb-4\"><a href=\"#\">World Wide Donation</a></h3>\r\n");
      out.write("                <p class=\"time-loc\"><span class=\"mr-2\"><i class=\"icon-clock-o\"></i> 10:30AM-03:30PM</span> <span><i class=\"icon-map-o\"></i> Venue Main Campus</span></p>\r\n");
      out.write("                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("                <p><a href=\"event.html\">Join Event <i class=\"ion-ios-arrow-forward\"></i></a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("          	<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("              <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/event-2.jpg');\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text p-4 d-block\">\r\n");
      out.write("              	<div class=\"meta mb-3\">\r\n");
      out.write("                  <div><a href=\"#\">Sep. 10, 2018</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"heading mb-4\"><a href=\"#\">World Wide Donation</a></h3>\r\n");
      out.write("                <p class=\"time-loc\"><span class=\"mr-2\"><i class=\"icon-clock-o\"></i> 10:30AM-03:30PM</span> <span><i class=\"icon-map-o\"></i> Venue Main Campus</span></p>\r\n");
      out.write("                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("                <p><a href=\"event.html\">Join Event <i class=\"ion-ios-arrow-forward\"></i></a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("          	<div class=\"blog-entry align-self-stretch\">\r\n");
      out.write("              <a href=\"blog-single.html\" class=\"block-20\" style=\"background-image: url('images/event-3.jpg');\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text p-4 d-block\">\r\n");
      out.write("              	<div class=\"meta mb-3\">\r\n");
      out.write("                  <div><a href=\"#\">Sep. 10, 2018</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"heading mb-4\"><a href=\"#\">World Wide Donation</a></h3>\r\n");
      out.write("                <p class=\"time-loc\"><span class=\"mr-2\"><i class=\"icon-clock-o\"></i> 10:30AM-03:30PM</span> <span><i class=\"icon-map-o\"></i> Venue Main Campus</span></p>\r\n");
      out.write("                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\r\n");
      out.write("                <p><a href=\"event.html\">Join Event <i class=\"ion-ios-arrow-forward\"></i></a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("		\r\n");
      out.write("		<section class=\"ftco-section-3 img\" style=\"background-image: url(images/bg_3.jpg);\">\r\n");
      out.write("    	<div class=\"overlay\"></div>\r\n");
      out.write("    	<div class=\"container\">\r\n");
      out.write("    		<div class=\"row d-md-flex\">\r\n");
      out.write("    		<div class=\"col-md-6 d-flex ftco-animate\">\r\n");
      out.write("    			<div class=\"img img-2 align-self-stretch\" style=\"background-image: url(images/bg_4.jpg);\"></div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"col-md-6 volunteer pl-md-5 ftco-animate\">\r\n");
      out.write("    			<h3 class=\"mb-3\">Be a volunteer</h3>\r\n");
      out.write("    			<form action=\"#\" class=\"volunter-form\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" placeholder=\"Your Name\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" placeholder=\"Your Email\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <textarea name=\"\" id=\"\" cols=\"30\" rows=\"3\" class=\"form-control\" placeholder=\"Message\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <input type=\"submit\" value=\"Send Message\" class=\"btn btn-white py-3 px-5\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("    		</div>    			\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"ftco-footer ftco-section img\">\r\n");
      out.write("    	<div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">About Us</h2>\r\n");
      out.write("              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("              <ul class=\"ftco-footer-social list-unstyled float-md-left float-lft mt-5\">\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Recent Blog</h2>\r\n");
      out.write("              <div class=\"block-21 mb-4 d-flex\">\r\n");
      out.write("                <a class=\"blog-img mr-4\" style=\"background-image: url(images/image_1.jpg);\"></a>\r\n");
      out.write("                <div class=\"text\">\r\n");
      out.write("                  <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about</a></h3>\r\n");
      out.write("                  <div class=\"meta\">\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-calendar\"></span> July 12, 2018</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-person\"></span> Admin</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-chat\"></span> 19</a></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"block-21 mb-4 d-flex\">\r\n");
      out.write("                <a class=\"blog-img mr-4\" style=\"background-image: url(images/image_2.jpg);\"></a>\r\n");
      out.write("                <div class=\"text\">\r\n");
      out.write("                  <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about</a></h3>\r\n");
      out.write("                  <div class=\"meta\">\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-calendar\"></span> July 12, 2018</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-person\"></span> Admin</a></div>\r\n");
      out.write("                    <div><a href=\"#\"><span class=\"icon-chat\"></span> 19</a></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-2\">\r\n");
      out.write("             <div class=\"ftco-footer-widget mb-4 ml-md-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Site Links</h2>\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">About</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Donate</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Causes</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Event</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Blog</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("            	<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("            	<div class=\"block-23 mb-3\">\r\n");
      out.write("	              <ul>\r\n");
      out.write("	                <li><span class=\"icon icon-map-marker\"></span><span class=\"text\">203 Fake St. Mountain View, San Francisco, California, USA</span></li>\r\n");
      out.write("	                <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span class=\"text\">+2 392 3929 210</span></a></li>\r\n");
      out.write("	                <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("	              </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"icon-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"js/aos.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("  <script src=\"js/google-map.js\"></script>\r\n");
      out.write("  <script src=\"js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
